// <auto-generated>
/*
 * DevInbox.ApiService | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using DevInbox.Client.Client;
using DevInbox.Client.Model;
using System.Diagnostics.CodeAnalysis;

namespace DevInbox.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IMailboxesApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        MailboxesApiEvents Events { get; }

        /// <summary>
        /// Create a new mailbox
        /// </summary>
        /// <remarks>
        /// Creates a new mailbox for receiving test emails. If no name is provided, a temporary mailbox is created.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailboxCreateModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateMailboxApiResponse"/>&gt;</returns>
        Task<ICreateMailboxApiResponse> CreateMailboxAsync(MailboxCreateModel mailboxCreateModel, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a new mailbox
        /// </summary>
        /// <remarks>
        /// Creates a new mailbox for receiving test emails. If no name is provided, a temporary mailbox is created.
        /// </remarks>
        /// <param name="mailboxCreateModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateMailboxApiResponse"/>?&gt;</returns>
        Task<ICreateMailboxApiResponse?> CreateMailboxOrDefaultAsync(MailboxCreateModel mailboxCreateModel, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="ICreateMailboxApiResponse"/>
    /// </summary>
    public interface ICreateMailboxApiResponse : DevInbox.Client.Client.IApiResponse, IOk<DevInbox.Client.Model.MailboxViewModel?>, IBadRequest<DevInbox.Client.Model.ProblemDetails?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class MailboxesApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnCreateMailbox;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorCreateMailbox;

        internal void ExecuteOnCreateMailbox(MailboxesApi.CreateMailboxApiResponse apiResponse)
        {
            OnCreateMailbox?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorCreateMailbox(Exception exception)
        {
            OnErrorCreateMailbox?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class MailboxesApi : IMailboxesApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<MailboxesApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public MailboxesApiEvents Events { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="MailboxesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MailboxesApi(ILogger<MailboxesApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, MailboxesApiEvents mailboxesApiEvents)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<MailboxesApi>();
            HttpClient = httpClient;
            Events = mailboxesApiEvents;
        }

        partial void FormatCreateMailbox(MailboxCreateModel mailboxCreateModel);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="mailboxCreateModel"></param>
        /// <returns></returns>
        private void ValidateCreateMailbox(MailboxCreateModel mailboxCreateModel)
        {
            if (mailboxCreateModel == null)
                throw new ArgumentNullException(nameof(mailboxCreateModel));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="mailboxCreateModel"></param>
        private void AfterCreateMailboxDefaultImplementation(ICreateMailboxApiResponse apiResponseLocalVar, MailboxCreateModel mailboxCreateModel)
        {
            bool suppressDefaultLog = false;
            AfterCreateMailbox(ref suppressDefaultLog, apiResponseLocalVar, mailboxCreateModel);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="mailboxCreateModel"></param>
        partial void AfterCreateMailbox(ref bool suppressDefaultLog, ICreateMailboxApiResponse apiResponseLocalVar, MailboxCreateModel mailboxCreateModel);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="mailboxCreateModel"></param>
        private void OnErrorCreateMailboxDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, MailboxCreateModel mailboxCreateModel)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorCreateMailbox(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, mailboxCreateModel);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="mailboxCreateModel"></param>
        partial void OnErrorCreateMailbox(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, MailboxCreateModel mailboxCreateModel);

        /// <summary>
        /// Create a new mailbox Creates a new mailbox for receiving test emails. If no name is provided, a temporary mailbox is created.
        /// </summary>
        /// <param name="mailboxCreateModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateMailboxApiResponse"/>&gt;</returns>
        public async Task<ICreateMailboxApiResponse?> CreateMailboxOrDefaultAsync(MailboxCreateModel mailboxCreateModel, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await CreateMailboxAsync(mailboxCreateModel, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Create a new mailbox Creates a new mailbox for receiving test emails. If no name is provided, a temporary mailbox is created.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="mailboxCreateModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ICreateMailboxApiResponse"/>&gt;</returns>
        public async Task<ICreateMailboxApiResponse> CreateMailboxAsync(MailboxCreateModel mailboxCreateModel, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateCreateMailbox(mailboxCreateModel);

                FormatCreateMailbox(mailboxCreateModel);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/mailboxes"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/mailboxes");

                    httpRequestMessageLocalVar.Content = (mailboxCreateModel as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(mailboxCreateModel, _jsonSerializerOptions));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json",
                        "application/problem+json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<CreateMailboxApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<CreateMailboxApiResponse>();
                        CreateMailboxApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/mailboxes", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterCreateMailboxDefaultImplementation(apiResponseLocalVar, mailboxCreateModel);

                        Events.ExecuteOnCreateMailbox(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorCreateMailboxDefaultImplementation(e, "/mailboxes", uriBuilderLocalVar.Path, mailboxCreateModel);
                Events.ExecuteOnErrorCreateMailbox(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="CreateMailboxApiResponse"/>
        /// </summary>
        public partial class CreateMailboxApiResponse : DevInbox.Client.Client.ApiResponse, ICreateMailboxApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<CreateMailboxApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="CreateMailboxApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateMailboxApiResponse(ILogger<CreateMailboxApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="CreateMailboxApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public CreateMailboxApiResponse(ILogger<CreateMailboxApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public DevInbox.Client.Model.MailboxViewModel? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<DevInbox.Client.Model.MailboxViewModel>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out DevInbox.Client.Model.MailboxViewModel? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public DevInbox.Client.Model.ProblemDetails? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<DevInbox.Client.Model.ProblemDetails>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out DevInbox.Client.Model.ProblemDetails? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
