// <auto-generated>
/*
 * DevInbox.ApiService | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using DevInbox.Client.Client;

namespace DevInbox.Client.Model
{
    /// <summary>
    /// MailboxCreateModel
    /// </summary>
    public partial class MailboxCreateModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailboxCreateModel" /> class.
        /// </summary>
        /// <param name="name">Optional name for the mailbox. If not provided, a temporary mailbox will be created.</param>
        /// <param name="projectName">Name of the project to associate the mailbox with. If not provided, uses the default project.</param>
        /// <param name="isTemporary">Whether the mailbox should be temporary or persistent.</param>
        [JsonConstructor]
        public MailboxCreateModel(string? name = default, string? projectName = default, bool isTemporary = true)
        {
            Name = name;
            ProjectName = projectName;
            IsTemporary = isTemporary;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Optional name for the mailbox. If not provided, a temporary mailbox will be created.
        /// </summary>
        /// <value>Optional name for the mailbox. If not provided, a temporary mailbox will be created.</value>
        [JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Name of the project to associate the mailbox with. If not provided, uses the default project.
        /// </summary>
        /// <value>Name of the project to associate the mailbox with. If not provided, uses the default project.</value>
        [JsonPropertyName("projectName")]
        public string? ProjectName { get; set; }

        /// <summary>
        /// Whether the mailbox should be temporary or persistent.
        /// </summary>
        /// <value>Whether the mailbox should be temporary or persistent.</value>
        [JsonPropertyName("isTemporary")]
        public bool IsTemporary { get; set; } = true;

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailboxCreateModel {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ProjectName: ").Append(ProjectName).Append("\n");
            sb.Append("  IsTemporary: ").Append(IsTemporary).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 100.", new [] { "Name" });
            }

            // ProjectName (string) maxLength
            if (this.ProjectName != null && this.ProjectName.Length > 100)
            {
                yield return new ValidationResult("Invalid value for ProjectName, length must be less than 100.", new [] { "ProjectName" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MailboxCreateModel" />
    /// </summary>
    public class MailboxCreateModelJsonConverter : JsonConverter<MailboxCreateModel>
    {
        /// <summary>
        /// Deserializes json to <see cref="MailboxCreateModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MailboxCreateModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> projectName = default;
            Option<bool?> isTemporary = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "projectName":
                            projectName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "isTemporary":
                            isTemporary = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            // name and projectName are optional, so we don't throw if they're not set
            return new MailboxCreateModel(
                name.IsSet ? name.Value! : default,
                projectName.IsSet ? projectName.Value! : default,
                isTemporary.IsSet && isTemporary.Value.HasValue ? isTemporary.Value!.Value : true);
        }

        /// <summary>
        /// Serializes a <see cref="MailboxCreateModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailboxCreateModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MailboxCreateModel mailboxCreateModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mailboxCreateModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MailboxCreateModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mailboxCreateModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MailboxCreateModel mailboxCreateModel, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mailboxCreateModel.Name != null)
                writer.WriteString("name", mailboxCreateModel.Name);
            else
                writer.WriteNull("name");

            if (mailboxCreateModel.ProjectName != null)
                writer.WriteString("projectName", mailboxCreateModel.ProjectName);
            else
                writer.WriteNull("projectName");

            writer.WriteBoolean("isTemporary", mailboxCreateModel.IsTemporary);
        }
    }
}
