// <auto-generated>
/*
 * DevInbox.ApiService | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using DevInbox.Client.Client;

namespace DevInbox.Client.Model
{
    /// <summary>
    /// MessageViewModel
    /// </summary>
    public partial class MessageViewModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MessageViewModel" /> class.
        /// </summary>
        /// <param name="uniqueId">Unique identifier for the message</param>
        /// <param name="isHtml">Whether the email body is HTML format</param>
        /// <param name="received">Timestamp when the message was received</param>
        /// <param name="from">Array of sender email addresses</param>
        /// <param name="to">Array of recipient email addresses</param>
        /// <param name="cc">Array of CC email addresses</param>
        /// <param name="bcc">Array of BCC email addresses</param>
        /// <param name="subject">Email subject line</param>
        /// <param name="body">Email body content</param>
        [JsonConstructor]
        public MessageViewModel(Guid uniqueId, bool isHtml, DateTime received, List<string>? from = default, List<string>? to = default, List<string>? cc = default, List<string>? bcc = default, string? subject = default, string? body = default)
        {
            UniqueId = uniqueId;
            IsHtml = isHtml;
            Received = received;
            From = from;
            To = to;
            Cc = cc;
            Bcc = bcc;
            Subject = subject;
            Body = body;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Unique identifier for the message
        /// </summary>
        /// <value>Unique identifier for the message</value>
        [JsonPropertyName("uniqueId")]
        public Guid UniqueId { get; set; }

        /// <summary>
        /// Whether the email body is HTML format
        /// </summary>
        /// <value>Whether the email body is HTML format</value>
        [JsonPropertyName("isHtml")]
        public bool IsHtml { get; set; }

        /// <summary>
        /// Timestamp when the message was received
        /// </summary>
        /// <value>Timestamp when the message was received</value>
        [JsonPropertyName("received")]
        public DateTime Received { get; set; }

        /// <summary>
        /// Array of sender email addresses
        /// </summary>
        /// <value>Array of sender email addresses</value>
        [JsonPropertyName("from")]
        public List<string>? From { get; set; }

        /// <summary>
        /// Array of recipient email addresses
        /// </summary>
        /// <value>Array of recipient email addresses</value>
        [JsonPropertyName("to")]
        public List<string>? To { get; set; }

        /// <summary>
        /// Array of CC email addresses
        /// </summary>
        /// <value>Array of CC email addresses</value>
        [JsonPropertyName("cc")]
        public List<string>? Cc { get; set; }

        /// <summary>
        /// Array of BCC email addresses
        /// </summary>
        /// <value>Array of BCC email addresses</value>
        [JsonPropertyName("bcc")]
        public List<string>? Bcc { get; set; }

        /// <summary>
        /// Email subject line
        /// </summary>
        /// <value>Email subject line</value>
        [JsonPropertyName("subject")]
        public string? Subject { get; set; }

        /// <summary>
        /// Email body content
        /// </summary>
        /// <value>Email body content</value>
        [JsonPropertyName("body")]
        public string? Body { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MessageViewModel {\n");
            sb.Append("  UniqueId: ").Append(UniqueId).Append("\n");
            sb.Append("  IsHtml: ").Append(IsHtml).Append("\n");
            sb.Append("  Received: ").Append(Received).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Cc: ").Append(Cc).Append("\n");
            sb.Append("  Bcc: ").Append(Bcc).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MessageViewModel" />
    /// </summary>
    public class MessageViewModelJsonConverter : JsonConverter<MessageViewModel>
    {
        /// <summary>
        /// The format to use to serialize Received
        /// </summary>
        public static string ReceivedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="MessageViewModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MessageViewModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> uniqueId = default;
            Option<bool?> isHtml = default;
            Option<DateTime?> received = default;
            Option<List<string>?> from = default;
            Option<List<string>?> to = default;
            Option<List<string>?> cc = default;
            Option<List<string>?> bcc = default;
            Option<string?> subject = default;
            Option<string?> body = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "uniqueId":
                            uniqueId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "isHtml":
                            isHtml = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "received":
                            received = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "from":
                            from = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "to":
                            to = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "cc":
                            cc = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "bcc":
                            bcc = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "subject":
                            subject = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "body":
                            body = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!uniqueId.IsSet)
                throw new ArgumentException("Property is required for class MessageViewModel.", nameof(uniqueId));

            if (!isHtml.IsSet)
                throw new ArgumentException("Property is required for class MessageViewModel.", nameof(isHtml));

            if (!received.IsSet)
                throw new ArgumentException("Property is required for class MessageViewModel.", nameof(received));

            if (!from.IsSet)
                throw new ArgumentException("Property is required for class MessageViewModel.", nameof(from));

            if (!to.IsSet)
                throw new ArgumentException("Property is required for class MessageViewModel.", nameof(to));

            if (!cc.IsSet)
                throw new ArgumentException("Property is required for class MessageViewModel.", nameof(cc));

            if (!bcc.IsSet)
                throw new ArgumentException("Property is required for class MessageViewModel.", nameof(bcc));

            if (!subject.IsSet)
                throw new ArgumentException("Property is required for class MessageViewModel.", nameof(subject));

            if (!body.IsSet)
                throw new ArgumentException("Property is required for class MessageViewModel.", nameof(body));

            if (uniqueId.IsSet && uniqueId.Value == null)
                throw new ArgumentNullException(nameof(uniqueId), "Property is not nullable for class MessageViewModel.");

            if (isHtml.IsSet && isHtml.Value == null)
                throw new ArgumentNullException(nameof(isHtml), "Property is not nullable for class MessageViewModel.");

            if (received.IsSet && received.Value == null)
                throw new ArgumentNullException(nameof(received), "Property is not nullable for class MessageViewModel.");

            return new MessageViewModel(uniqueId.Value!.Value!, isHtml.Value!.Value!, received.Value!.Value!, from.Value!, to.Value!, cc.Value!, bcc.Value!, subject.Value!, body.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="MessageViewModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="messageViewModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MessageViewModel messageViewModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, messageViewModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MessageViewModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="messageViewModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MessageViewModel messageViewModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteString("uniqueId", messageViewModel.UniqueId);

            writer.WriteBoolean("isHtml", messageViewModel.IsHtml);

            writer.WriteString("received", messageViewModel.Received.ToString(ReceivedFormat));

            if (messageViewModel.From != null)
            {
                writer.WritePropertyName("from");
                JsonSerializer.Serialize(writer, messageViewModel.From, jsonSerializerOptions);
            }
            else
                writer.WriteNull("from");
            if (messageViewModel.To != null)
            {
                writer.WritePropertyName("to");
                JsonSerializer.Serialize(writer, messageViewModel.To, jsonSerializerOptions);
            }
            else
                writer.WriteNull("to");
            if (messageViewModel.Cc != null)
            {
                writer.WritePropertyName("cc");
                JsonSerializer.Serialize(writer, messageViewModel.Cc, jsonSerializerOptions);
            }
            else
                writer.WriteNull("cc");
            if (messageViewModel.Bcc != null)
            {
                writer.WritePropertyName("bcc");
                JsonSerializer.Serialize(writer, messageViewModel.Bcc, jsonSerializerOptions);
            }
            else
                writer.WriteNull("bcc");
            if (messageViewModel.Subject != null)
                writer.WriteString("subject", messageViewModel.Subject);
            else
                writer.WriteNull("subject");

            if (messageViewModel.Body != null)
                writer.WriteString("body", messageViewModel.Body);
            else
                writer.WriteNull("body");
        }
    }
}
