/*
 * DevInbox.ApiService | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Security.Cryptography;
using DevInbox.Client.Client;
using DevInbox.Client.Api;
using DevInbox.Client.Extensions;
using Xunit;

namespace DevInbox.Client.Test.Api
{
    /// <summary>
    ///  Tests the dependency injection.
    /// </summary>
    public class DependencyInjectionTest
    {
        private readonly IHost _hostUsingConfigureWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {

            })
            .Build();

        private readonly IHost _hostUsingConfigureWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {

                options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
            })
            .Build();

        private readonly IHost _hostUsingAddWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {

                });
            })
            .Build();

        private readonly IHost _hostUsingAddWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {

                    options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
                });
            })
            .Build();

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithAClientTest()
        {
            var mailboxesApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IMailboxesApi>();
            Assert.True(mailboxesApi.HttpClient.BaseAddress != null);

            var messagesApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IMessagesApi>();
            Assert.True(messagesApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithoutAClientTest()
        {
            var mailboxesApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IMailboxesApi>();
            Assert.True(mailboxesApi.HttpClient.BaseAddress != null);

            var messagesApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IMessagesApi>();
            Assert.True(messagesApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithAClientTest()
        {
            var mailboxesApi = _hostUsingAddWithAClient.Services.GetRequiredService<IMailboxesApi>();
            Assert.True(mailboxesApi.HttpClient.BaseAddress != null);
            
            var messagesApi = _hostUsingAddWithAClient.Services.GetRequiredService<IMessagesApi>();
            Assert.True(messagesApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithoutAClientTest()
        {
            var mailboxesApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IMailboxesApi>();
            Assert.True(mailboxesApi.HttpClient.BaseAddress != null);

            var messagesApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IMessagesApi>();
            Assert.True(messagesApi.HttpClient.BaseAddress != null);
        }
    }
}
