/*
 * DevInbox.ApiService | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using DevInbox.Client.Api;
using DevInbox.Client.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace DevInbox.Client.Test.Api
{
    /// <summary>
    ///  Class for testing MessagesApi
    /// </summary>
    public sealed class MessagesApiTests : ApiTestsBase
    {
        private readonly IMessagesApi _instance;

        public MessagesApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IMessagesApi>();
        }

        /// <summary>
        /// Test GetLastMessage
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetLastMessageAsyncTest()
        {
            string key = default!;
            var response = await _instance.GetLastMessageAsync(key);
            var model = response.Ok();
            Assert.IsType<MessageViewModel>(model);
        }

        /// <summary>
        /// Test GetLastMessageWithTemplate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetLastMessageWithTemplateAsyncTest()
        {
            string key = default!;
            string template = default!;
            var response = await _instance.GetLastMessageWithTemplateAsync(key, template);
            var model = response.Ok();
            Assert.IsType<MessageParsedViewModel>(model);
        }

        /// <summary>
        /// Test GetMessageById
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetMessageByIdAsyncTest()
        {
            string key = default!;
            Guid id = default!;
            var response = await _instance.GetMessageByIdAsync(key, id);
            var model = response.Ok();
            Assert.IsType<MessageViewModel>(model);
        }

        /// <summary>
        /// Test GetMessageCount
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetMessageCountAsyncTest()
        {
            string key = default!;
            var response = await _instance.GetMessageCountAsync(key);
            var model = response.Ok();
            Assert.IsType<MessageCountResult>(model);
        }

        /// <summary>
        /// Test GetMessages
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetMessagesAsyncTest()
        {
            string key = default!;
            Client.Option<int> skip = default!;
            Client.Option<int> take = default!;
            var response = await _instance.GetMessagesAsync(key, skip, take);
            var model = response.Ok();
            Assert.IsType<MessagesViewModel>(model);
        }

        /// <summary>
        /// Test GetSingleMessage
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetSingleMessageAsyncTest()
        {
            string key = default!;
            var response = await _instance.GetSingleMessageAsync(key);
            var model = response.Ok();
            Assert.IsType<MessageViewModel>(model);
        }

        /// <summary>
        /// Test GetSingleMessageWithTemplate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetSingleMessageWithTemplateAsyncTest()
        {
            string key = default!;
            string template = default!;
            var response = await _instance.GetSingleMessageWithTemplateAsync(key, template);
            var model = response.Ok();
            Assert.IsType<MessageParsedViewModel>(model);
        }
    }
}
