/*
 * DevInbox.ApiService | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DevInbox.Client.Model;
using DevInbox.Client.Client;
using System.Reflection;

namespace DevInbox.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MailboxViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MailboxViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MailboxViewModel
        //private MailboxViewModel instance;

        public MailboxViewModelTests()
        {
            // TODO uncomment below to create an instance of MailboxViewModel
            //instance = new MailboxViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MailboxViewModel
        /// </summary>
        [Fact]
        public void MailboxViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" MailboxViewModel
            //Assert.IsType<MailboxViewModel>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
    }
}
