/*
 * DevInbox.ApiService | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DevInbox.Client.Model;
using DevInbox.Client.Client;
using System.Reflection;

namespace DevInbox.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MailboxCreateModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MailboxCreateModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MailboxCreateModel
        //private MailboxCreateModel instance;

        public MailboxCreateModelTests()
        {
            // TODO uncomment below to create an instance of MailboxCreateModel
            //instance = new MailboxCreateModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MailboxCreateModel
        /// </summary>
        [Fact]
        public void MailboxCreateModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" MailboxCreateModel
            //Assert.IsType<MailboxCreateModel>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ProjectName'
        /// </summary>
        [Fact]
        public void ProjectNameTest()
        {
            // TODO unit test for the property 'ProjectName'
        }
    }
}
