/*
 * DevInbox.ApiService | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DevInbox.Client.Model;
using DevInbox.Client.Client;
using System.Reflection;

namespace DevInbox.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MessageParsedViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessageParsedViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessageParsedViewModel
        //private MessageParsedViewModel instance;

        public MessageParsedViewModelTests()
        {
            // TODO uncomment below to create an instance of MessageParsedViewModel
            //instance = new MessageParsedViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessageParsedViewModel
        /// </summary>
        [Fact]
        public void MessageParsedViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessageParsedViewModel
            //Assert.IsType<MessageParsedViewModel>(instance);
        }

        /// <summary>
        /// Test the property 'UniqueId'
        /// </summary>
        [Fact]
        public void UniqueIdTest()
        {
            // TODO unit test for the property 'UniqueId'
        }

        /// <summary>
        /// Test the property 'IsHtml'
        /// </summary>
        [Fact]
        public void IsHtmlTest()
        {
            // TODO unit test for the property 'IsHtml'
        }

        /// <summary>
        /// Test the property 'Received'
        /// </summary>
        [Fact]
        public void ReceivedTest()
        {
            // TODO unit test for the property 'Received'
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'Cc'
        /// </summary>
        [Fact]
        public void CcTest()
        {
            // TODO unit test for the property 'Cc'
        }

        /// <summary>
        /// Test the property 'Bcc'
        /// </summary>
        [Fact]
        public void BccTest()
        {
            // TODO unit test for the property 'Bcc'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }
    }
}
