/*
 * DevInbox.ApiService | v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DevInbox.Client.Model;
using DevInbox.Client.Client;
using System.Reflection;

namespace DevInbox.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MessagesViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessagesViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessagesViewModel
        //private MessagesViewModel instance;

        public MessagesViewModelTests()
        {
            // TODO uncomment below to create an instance of MessagesViewModel
            //instance = new MessagesViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessagesViewModel
        /// </summary>
        [Fact]
        public void MessagesViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessagesViewModel
            //Assert.IsType<MessagesViewModel>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
    }
}
