name: DevInbox-net
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Solution_Name: ./src/DevInbox.sln
      Test_Project: ./src/DevInbox.ApiTests/DevInbox.ApiTests.csproj
      Version: 1.0.1-beta
      DEVINBOX_API_KEY: ${{ secrets.DEVINBOX_API_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Clean output directory
      run: dotnet clean $Solution_Name -c Release
    
    - name: Test the project
      run: dotnet test $Test_Project
    
    - name: Build the packages
      run: dotnet build $Solution_Name -c Release /p:Version=$Version
  
    - name: Push Package to NuGet.org
      run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
